name: flutter_source_gen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  source_gen: ^2.0.0
  build_runner: ^2.4.15
  freezed: ^2.5.7
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
